services:
  - type: web
    name: ecommerce-api
    env: python
    buildCommand: pip install --no-cache-dir fastapi==0.89.1 uvicorn==0.22.0 typing-extensions==4.8.0
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health 